/*
 * gen_font.c — Build-time TrueType rasterizer using stb_truetype.
 * Runs on the HOST. Outputs a C file (build/gfx_font_data.c) with pre-rasterized
 * glyph bitmaps that the kernel links in directly (no float at runtime).
 *
 * Usage: ./gen_font <font.ttf> <px_height> <output.c>
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#define STB_TRUETYPE_IMPLEMENTATION
#include "../src/kernel/gfx/3rdparty/stb_truetype.h"

#define FIRST_CHAR   0x20   /* space */
#define LAST_CHAR    0x7E   /* ~ */
#define NUM_CHARS    (LAST_CHAR - FIRST_CHAR + 1)

int main(int argc, char **argv) {
    if (argc != 4) {
        fprintf(stderr, "Usage: %s <font.ttf> <px_height> <output.c>\n", argv[0]);
        return 1;
    }
    const char *ttf_path  = argv[1];
    int         px_height = atoi(argv[2]);
    const char *out_path  = argv[3];

    /* Load TTF file */
    FILE *f = fopen(ttf_path, "rb");
    if (!f) { fprintf(stderr, "Cannot open %s\n", ttf_path); return 1; }
    fseek(f, 0, SEEK_END);
    long fsz = ftell(f);
    rewind(f);
    uint8_t *ttf_buf = malloc(fsz);
    fread(ttf_buf, 1, fsz, f);
    fclose(f);

    stbtt_fontinfo font;
    if (!stbtt_InitFont(&font, ttf_buf, stbtt_GetFontOffsetForIndex(ttf_buf, 0))) {
        fprintf(stderr, "Failed to init font\n");
        return 1;
    }

    float scale = stbtt_ScaleForPixelHeight(&font, (float)px_height);

    int ascent, descent, line_gap;
    stbtt_GetFontVMetrics(&font, &ascent, &descent, &line_gap);
    int baseline    = (int)(ascent  * scale);
    int cell_height = (int)((ascent - descent) * scale);

    /* Find maximum advance width for a monospace cell */
    int cell_width = 0;
    for (int c = FIRST_CHAR; c <= LAST_CHAR; c++) {
        int adv, lsb;
        stbtt_GetCodepointHMetrics(&font, c, &adv, &lsb);
        int w = (int)(adv * scale + 0.5f);
        if (w > cell_width) cell_width = w;
    }

    printf("Font: %s  height=%dpx  cell=%dx%d\n",
           ttf_path, px_height, cell_width, cell_height);

    FILE *out = fopen(out_path, "w");
    if (!out) { fprintf(stderr, "Cannot write %s\n", out_path); return 1; }

    fprintf(out, "/* AUTO-GENERATED by gen_font — do not edit */\n");
    fprintf(out, "#include \"gfx/font.h\"\n\n");
    fprintf(out, "#define FONT_CELL_W  %d\n", cell_width);
    fprintf(out, "#define FONT_CELL_H  %d\n\n", cell_height);

    /* Rasterize each glyph into cell_width × cell_height bitmap */
    fprintf(out, "static const uint8_t _glyph_bitmaps[%d][%d] = {\n",
            NUM_CHARS, cell_width * cell_height);

    for (int c = FIRST_CHAR; c <= LAST_CHAR; c++) {
        int bw, bh, bx, by;
        uint8_t *bitmap = stbtt_GetCodepointBitmap(
                &font, 0, scale, c, &bw, &bh, &bx, &by);

        /* Build cell_width × cell_height buffer (zero-padded) */
        uint8_t *cell = calloc(cell_width * cell_height, 1);
        int y_off = baseline + by;  /* by is negative for glyphs above baseline */
        for (int row = 0; row < bh; row++) {
            int dst_row = y_off + row;
            if (dst_row < 0 || dst_row >= cell_height) continue;
            for (int col = 0; col < bw; col++) {
                int dst_col = bx + col;
                if (dst_col < 0 || dst_col >= cell_width) continue;
                cell[dst_row * cell_width + dst_col] = bitmap[row * bw + col];
            }
        }

        fprintf(out, "    /* '%c' (U+%04X) */\n    {", (c >= 0x20 && c < 0x7F) ? c : '?', c);
        for (int i = 0; i < cell_width * cell_height; i++) {
            if (i % cell_width == 0) fprintf(out, "\n        ");
            fprintf(out, "0x%02x,", cell[i]);
        }
        fprintf(out, "\n    },\n");

        stbtt_FreeBitmap(bitmap, NULL);
        free(cell);
    }

    fprintf(out, "};\n\n");

    /* Export the public descriptor */
    fprintf(out,
        "const gfx_font_atlas_t g_font_atlas = {\n"
        "    .cell_w    = FONT_CELL_W,\n"
        "    .cell_h    = FONT_CELL_H,\n"
        "    .first_char = 0x%02x,\n"
        "    .num_chars  = %d,\n"
        "    .bitmaps    = (const uint8_t *)_glyph_bitmaps,\n"
        "};\n", FIRST_CHAR, NUM_CHARS);

    fclose(out);
    free(ttf_buf);
    printf("Wrote %s  (%d glyphs @ %dx%d)\n", out_path, NUM_CHARS, cell_width, cell_height);
    return 0;
}
